import numpy as np
import pandas as pd
data = pd.read_csv('E:/BaiduNetdiskDownload/论文/论文/data.csv')
idlist = np.unique(data['id'])
data['feature'] = data['feature'].astype('str')
columns = np.unique(data['feature'])
columns = ['id', 'gender', 'age'] + columns.tolist() + ['result']
depre = pd.DataFrame(columns = columns)
depre['id'] = idlist
columns = np.unique(data['feature'])
for i in idlist:
    depre.loc[depre['id']== i, ['gender']] = data.loc[data['id'] == i]['gender'].values[0]
    depre.loc[depre['id']== i, ['age']] = data.loc[data['id'] == i]['age'].values[0]
    depre.loc[depre['id']== i, ['result']] = data.loc[data['id'] == i]['result'].values[0]
    for j in columns:
        if j in data.loc[data['id'] == i]['feature'].values:
            depre.loc[depre['id'] == i, [j]] = data[(data['id'] == i) & (data['feature'] == j)]['value'].values[0]
depre['age'] = depre['age'].apply(lambda x : x.replace('岁', ''))
depre.to_csv('E:/BaiduNetdiskDownload/论文/论文/data1.csv', index = 0)

In [1]:
import itertools
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.feature_selection import mutual_info_classif as MIF
import random
import os
# chain()可以把一组迭代对象串联起来，形成一个更大的迭代器
from itertools import chain
from tensorflow import keras
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras import optimizers, layers, losses, metrics
from tensorflow.keras.initializers import glorot_normal, he_normal
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Dense, Embedding, Lambda, multiply, Flatten, Concatenate
from sklearn.metrics import log_loss, roc_auc_score, accuracy_score, precision_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from sklearn.svm import OneClassSVM
from sklearn.ensemble import IsolationForest

from tensorflow.keras import backend as K
from tensorflow.keras.regularizers import l2

from deepctr.inputs import get_dense_input, create_embedding_matrix, embedding_lookup, get_dense_input, varlen_embedding_lookup, \
    get_varlen_pooling_list, mergeDict
from deepctr.layers.sequence import SequencePoolingLayer, Transformer, AttentionSequencePoolingLayer

from deepctr.feature_column import  SparseFeat, DenseFeat, VarLenSparseFeat, get_feature_names, build_input_features, get_linear_logit, DEFAULT_GROUP_NAME, input_from_feature_columns
from deepctr.layers.core import PredictionLayer, DNN
from deepctr.layers.interaction import FM, FEFMLayer, BiInteractionPooling, AFMLayer, CIN, InteractingLayer, FwFMLayer, InnerProductLayer, OutterProductLayer, FGCNNLayer, CrossNet,  CrossNetMix
from deepctr.layers.utils import concat_func, add_func, Hash, NoMask, combined_dnn_input, reduce_sum, softmax
from tensorflow.keras.layers import Layer
from tensorflow.keras.initializers import Zeros, glorot_normal, RandomNormal
import matplotlib.pyplot as plt
import matplotlib
# matplotlib.rcParams['font.family'] = 'Arial'
# matplotlib.rcParams['font.size'] = 12
# np.random.seed(1024) # seed是一个固定的整数即可
# random.seed(1024)
# os.environ['PYTHONHASHSEED'] = str(1024)

DeepCTR version 0.9.1 detected. Your version is 0.9.0.
Use `pip install -U deepctr` to upgrade.Changelog: https://github.com/shenweichen/DeepCTR/releases/tag/v0.9.1


# 预处理

In [2]:
depre = pd.read_csv('E:/BaiduDownload/论文/论文/data2.csv')
# pd.set_option('display.max_rows', None)
depre = depre.drop(['id', 'HFR', 'MFR', 'T-G', 'RET100', 'RETwell', 'IRF', 'TIBC', 'RET-He', 'FE','GSP', 'UIBC', 'LFR'], axis = 1)
np.unique(depre['result'])
depre=depre[~depre['result'].isin(['产后抑郁','适应障碍'])]
encoder = OrdinalEncoder()
depre.loc[:, ['gender', 'result']] = encoder.fit_transform(depre[['gender', 'result']])
print(encoder.categories_)
for i in ['age', 'gender', 'result']:
    depre.loc[:, i] = depre.loc[:, i].astype('int32')
depre

[array(['女', '男'], dtype=object), array(['抑郁发作', '抑郁状态', '抑郁症'], dtype=object)]


gender  age   A/B   A/G    ADA    AFU     AG    ALB     ALP    ALT  ...  \
0         0   76  0.82  1.51  11.59  26.39   9.40  40.94   70.81  18.71  ...   
1         0   44  1.83  1.42  22.68  21.53   9.30  41.57   59.45  23.15  ...   
2         0   79  2.81  1.43  11.88  31.29   9.80  45.43   98.66  26.83  ...   
3         0   79  1.24  1.22  10.44  25.16   5.70  38.43   68.37  11.35  ...   
4         0   63  1.00  1.54   7.73  24.53   8.40  39.45   91.96  13.46  ...   
..      ...  ...   ...   ...    ...    ...    ...    ...     ...    ...  ...   
634       0   19  1.95  2.08  11.14  24.80   8.90  40.55   59.57   8.43  ...   
635       0   73  0.95  1.06  16.72  28.24  12.60  35.30   89.68  14.73  ...   
636       0   52  1.34  1.58   6.03  19.00   9.18  39.70   35.71   7.78  ...   
637       0   13  1.26  1.63   9.21  35.65  12.98  46.79  106.79  43.82  ...   
638       0   18  1.83  1.89   6.46  27.61   7.10  42.69   59.38  10.05  ...   

        TP   TSH    TT   Tg-Ab      UA   WBC    eGFR  hs-CTNI      na  result  
0    68.00  2.31  17.2  0.8999  340.62  5.62   84.55    0.001  141.00       2  
1    70.78  2.80   NaN  1.2300  213.65  4.66  111.94      NaN  141.00       1  
2    77.20  1.42  17.5  0.8999  304.05  5.60     NaN    0.006  143.00       2  
3    69.84  3.39  17.9  0.8999  365.19  5.72     NaN      NaN  141.00       0  
4    65.05  1.32  17.3  0.8999  247.12  3.75   94.13      NaN  140.00       2  
..     ...   ...   ...     ...     ...   ...     ...      ...     ...     ...  
634  60.08  1.78  17.0  3.4000  404.22  4.98  109.20      NaN  139.00       1  
635  68.67  1.28  19.9  0.8999  228.84  6.90   81.24    0.001  140.00       2  
636  64.77   NaN  16.7     NaN  185.39  6.14  102.73      NaN  140.37       2  
637  75.42  2.75  17.6  0.8999  508.45  9.21  144.95      NaN  136.79       1  
638  65.33  4.27  16.7  0.8999  197.29  9.06  133.94      NaN  139.63       1  

[636 rows x 109 columns]

In [3]:
depre = depre.reset_index(drop = True)

In [4]:
for i in range(depre['result'].size):
    if depre.loc[i, 'result'] != None:
        if depre.loc[i, 'result'] == 0 or depre.loc[i, 'result'] == 1:
            depre.loc[i, 'result'] = 0
        else:
            depre.loc[i, 'result'] = 1

In [5]:
dict(depre.loc[:, 'result'].value_counts())

{0: 501, 1: 135}

In [12]:
depre1 = depre.copy()
# impute = SimpleImputer(strategy = "mean" )
# depre1.loc[:] = impute.fit_transform(depre1.loc[:])
depre1 = depre1.fillna(0)
depre1 = depre1.sample(frac=1.0,random_state=42)
depre1 = depre1.reset_index(drop = True)
data1 = depre1.drop(columns=['result'])
labe = depre1['result']
data2 = data1.copy()

In [13]:
# dat, test, lab, label1 = train_test_split(data1, labe, test_size = 0.3)
train, test, label, label1 = train_test_split(data1, labe, test_size = 0.3, random_state = 42)

In [14]:
data = train.append(test)
sparse_features=['gender', 'age']
dense_features = list(set(data.columns.tolist()).difference(set(sparse_features)))

# 离散型数据进行标签化处理
for feat in sparse_features:
    lbe = LabelEncoder()
    data[feat] = lbe.fit_transform(data[feat])
# 连续型数据进行归一化处理，使其范围在（0，1）
mms = MinMaxScaler(feature_range=(0, 1))
data[dense_features] = mms.fit_transform(data[dense_features])

# 2.count #unique features for each sparse field,and record dense feature field name

fixlen_feature_columns = [SparseFeat(feat, vocabulary_size=data[feat].nunique(),embedding_dim=4)
                        for i,feat in enumerate(sparse_features)] + [DenseFeat(feat, 1,)
                        for feat in dense_features]

dnn_feature_columns = fixlen_feature_columns
linear_feature_columns = fixlen_feature_columns

feature_names = get_feature_names(linear_feature_columns + dnn_feature_columns)

# 3.generate input deepfm_data for model
# train, test = train_test_split(deepfm_data, test_size=0.2)

deepfm_train = data.head(train.shape[0])
deepfm_test = data.tail(test.shape[0])

deepfm_train = {name:deepfm_train[name] for name in feature_names}
deepfm_test = {name:deepfm_test[name] for name in feature_names}

In [15]:
def class_balanced_sigmoid_cross_entropy(label, logits):
    y = tf.cast(label, tf.float32)
    logits = tf.cast(logits, tf.float32)
    count_neg = tf.reduce_sum(1. - y) # the number of 0 in y
    count_pos = tf.reduce_sum(y) # the number of 1 in y (less than count_neg)
    beta = count_neg / (count_neg + count_pos)

    pos_weight = beta / (1 - beta)
    cost = tf.nn.weighted_cross_entropy_with_logits(y, logits, pos_weight)
    cost = tf.reduce_mean(cost * (1 - beta))
    return cost

In [16]:
def focal_loss(gamma=2., alpha=0.25):
 
    def focal_loss_fixed(y_true, y_pred):
        pt_1 = tf.where(tf.equal(y_true, 1), y_pred, tf.ones_like(y_pred))
        pt_0 = tf.where(tf.equal(y_true, 0), y_pred, tf.zeros_like(y_pred))
        loss = -tf.reduce_sum(alpha * tf.pow(1. - pt_1, gamma) * tf.math.log(1e-07+pt_1)) \
           -tf.reduce_sum((1-alpha) * tf.pow( pt_0, gamma) * tf.math.log(1. - pt_0 + 1e-07))
        return loss
    return focal_loss_fixed

In [42]:
def ENFM(linear_feature_columns, dnn_feature_columns, dnn_hidden_units=(256, 128, 64),
            cin_layer_size=(128, 128,), cin_split_half=True, cin_activation='relu', l2_reg_linear=0.00001,
            l2_reg_embedding=0.00001, l2_reg_dnn=0, l2_reg_cin=0, seed=1024, bi_dropout=0, dnn_dropout=0,
            dnn_activation='relu', dnn_use_bn=False, task='binary'):


    features = build_input_features(
        linear_feature_columns + dnn_feature_columns)

    inputs_list = list(features.values())

    linear_logit = get_linear_logit(features, linear_feature_columns, seed=seed, prefix='linear',
                                    l2_reg=l2_reg_linear)

    sparse_embedding_list, dense_value_list = input_from_feature_columns(features, dnn_feature_columns,
                                                                         l2_reg_embedding, seed)

    fm_input = concat_func(sparse_embedding_list, axis=1)

#     dnn_input = combined_dnn_input(sparse_embedding_list, dense_value_list)
#     dnn_output = DNN(dnn_hidden_units, dnn_activation, l2_reg_dnn, dnn_dropout, dnn_use_bn, seed=seed)(dnn_input)
#     dnn_logit = tf.keras.layers.Dense(
#         1, use_bias=False, kernel_initializer=tf.keras.initializers.glorot_normal(seed))(dnn_output)

    bi_out = BiInteractionPooling()(fm_input)
    if bi_dropout:
        bi_out = tf.keras.layers.Dropout(bi_dropout)(bi_out, training=None)
    dnn_input = combined_dnn_input([bi_out], dense_value_list)
    dnn_output = DNN(dnn_hidden_units, dnn_activation, l2_reg_dnn, dnn_dropout, False, seed=seed)(dnn_input)
    dnn_logit = tf.keras.layers.Dense(
        1, use_bias=False, kernel_initializer=tf.keras.initializers.glorot_normal(seed))(dnn_output)

    final_logit = add_func([linear_logit, dnn_logit])

    if len(cin_layer_size) > 0:
        exFM_out = CIN(cin_layer_size, cin_activation,
                       cin_split_half, l2_reg_cin, seed)(fm_input)
        exFM_logit = tf.keras.layers.Dense(1, kernel_initializer=tf.keras.initializers.glorot_normal(seed))(exFM_out)
        final_logit = add_func([final_logit, exFM_logit])

    output = PredictionLayer(task)(final_logit)

    model = tf.keras.models.Model(inputs=inputs_list, outputs=output)
    model.compile(optimizer=optimizers.Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0), 
            loss=losses.BinaryCrossentropy(), 
            metrics=['AUC', 'binary_accuracy', 'Precision', 'Recall'])
    return model

In [51]:
metrics = []
lrs = np.arange(0, 1, 0.1)
for i in lrs:
    metric = []
    for j in range(3):
        model = ENFM(linear_feature_columns, dnn_feature_columns, dnn_hidden_units=(256, 128, 64),
            cin_layer_size=(128, 128,), cin_split_half=True, cin_activation='relu', l2_reg_linear=0.3,
            l2_reg_embedding=0.5, l2_reg_dnn=0, l2_reg_cin=0, seed=1024, bi_dropout=0, dnn_dropout=0.2,
            dnn_activation='relu', dnn_use_bn=False, task='binary')
        input_train = deepfm_train
        model.fit(input_train,
                        label,
                        validation_split=0.2,
                        epochs=100,
                        batch_size=128,
                        shuffle = False,
                        verbose = 1, 
                        callbacks=[EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)],)
        input_test = deepfm_test
        ans_mtx = model.predict(input_test, batch_size=100)
        loss, auc, acc, pre, rec = model.evaluate(input_test, label1)
        metric.append([loss, auc, acc, pre, rec])
    metric = np.array(metric)
    print(metric)
    metrics.append(metric)
print(metrics)

Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 1.2468 - auc: 0.4932 - binary_accuracy: 0.6320 - precision: 0.1927 - recall: 0.3281 - val_loss: 1.2503 - val_auc: 0.3507 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 308ms/step - loss: 1.0838 - auc: 0.4886 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3500 - val_auc: 0.3282 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 292ms/step - loss: 1.0720 - auc: 0.5007 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3694 - val_auc: 0.3261 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 4/100
3/3 [==============================] - 1s 285ms/step - loss: 1.0537 - auc: 0.5089 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.

6/6 [==============================] - 0s 79ms/step - loss: 0.7979 - auc: 0.5994 - binary_accuracy: 0.7696 - precision: 0.0000e+00 - recall: 0.0000e+00 0s - loss: 0.7823 - auc: 0.6554 - binary_accuracy: 0.7625 - precision: 0.0000e+00 - recall: 0.0000
Epoch 1/100
3/3 [==============================] - 9s 3s/step - loss: 1.2142 - auc: 0.4905 - binary_accuracy: 0.6938 - precision: 0.1429 - recall: 0.1406 - val_loss: 1.2582 - val_auc: 0.3381 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 379ms/step - loss: 1.0787 - auc: 0.4856 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3528 - val_auc: 0.3173 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 383ms/step - loss: 1.0689 - auc: 0.4981 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3480 - val_

6/6 [==============================] - 1s 97ms/step - loss: 0.7863 - auc: 0.5783 - binary_accuracy: 0.7330 - precision: 0.2143 - recall: 0.0698
Epoch 1/100
3/3 [==============================] - 8s 3s/step - loss: 1.2734 - auc: 0.4938 - binary_accuracy: 0.5843 - precision: 0.1769 - recall: 0.3594 - val_loss: 1.2803 - val_auc: 0.2986 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 2s 606ms/step - loss: 1.0805 - auc: 0.4868 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.4047 - val_auc: 0.2804 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 360ms/step - loss: 1.0816 - auc: 0.4893 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3705 - val_auc: 0.2693 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 4/100


6/6 [==============================] - 1s 86ms/step - loss: 0.7820 - auc: 0.5945 - binary_accuracy: 0.7592 - precision: 0.0000e+00 - recall: 0.0000e+00
[[0.79791534 0.59938717 0.76963353 0.         0.        ]
 [0.78631949 0.57825267 0.7329843  0.21428572 0.06976745]
 [0.78203768 0.59451604 0.75916231 0.         0.        ]]
Epoch 1/100
3/3 [==============================] - 9s 3s/step - loss: 1.1694 - auc: 0.4984 - binary_accuracy: 0.7697 - precision: 0.1786 - recall: 0.0781 - val_loss: 1.3193 - val_auc: 0.3407 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 368ms/step - loss: 1.0807 - auc: 0.5097 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3908 - val_auc: 0.3197 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 2s 617ms/step - loss: 1.0768 - auc: 0.4573 - binary_accuracy: 0

6/6 [==============================] - 1s 91ms/step - loss: 0.7465 - auc: 0.5811 - binary_accuracy: 0.7749 - precision: 0.5000 - recall: 0.0233- ETA: 0s - loss: 0.7320 - auc: 0.6279 - binary_accuracy: 0.7688 - precision: 0.5000 - recall: 0.
Epoch 1/100
3/3 [==============================] - 9s 3s/step - loss: 1.2465 - auc: 0.4945 - binary_accuracy: 0.6348 - precision: 0.1700 - recall: 0.2656 - val_loss: 1.2494 - val_auc: 0.3627 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 409ms/step - loss: 1.0837 - auc: 0.5135 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3449 - val_auc: 0.3671 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 408ms/step - loss: 1.0785 - auc: 0.4533 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3594 - val_auc: 0.377

6/6 [==============================] - 0s 82ms/step - loss: 0.7592 - auc: 0.5820 - binary_accuracy: 0.7644 - precision: 0.2500 - recall: 0.0233
Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 1.3254 - auc: 0.5159 - binary_accuracy: 0.5253 - precision: 0.1856 - recall: 0.4844 - val_loss: 1.2482 - val_auc: 0.3563 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 360ms/step - loss: 1.0915 - auc: 0.4980 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3465 - val_auc: 0.3097 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 369ms/step - loss: 1.0756 - auc: 0.5089 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3838 - val_auc: 0.3001 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 4/100


6/6 [==============================] - 0s 80ms/step - loss: 0.7348 - auc: 0.5788 - binary_accuracy: 0.7644 - precision: 0.4167 - recall: 0.1163
[[0.7464956  0.58108109 0.77486908 0.5        0.02325581]
 [0.75923735 0.58202386 0.76439792 0.25       0.02325581]
 [0.73478353 0.57880265 0.76439792 0.41666666 0.11627907]]
Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 1.2254 - auc: 0.4816 - binary_accuracy: 0.6882 - precision: 0.2099 - recall: 0.2656 - val_loss: 1.2728 - val_auc: 0.3525 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 360ms/step - loss: 1.0873 - auc: 0.4587 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3663 - val_auc: 0.3159 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 358ms/step - loss: 1.0827 - auc: 0.4980 - binary_accuracy: 0.8202 - 

6/6 [==============================] - 0s 82ms/step - loss: 0.7045 - auc: 0.5833 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 1/100
3/3 [==============================] - 10s 3s/step - loss: 1.3245 - auc: 0.4925 - binary_accuracy: 0.5253 - precision: 0.1779 - recall: 0.4531 - val_loss: 1.2457 - val_auc: 0.3721 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 277ms/step - loss: 1.0915 - auc: 0.4898 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3366 - val_auc: 0.3566 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 2s 532ms/step - loss: 1.0770 - auc: 0.5217 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3678 - val_auc: 0.3498 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epo

6/6 [==============================] - 1s 91ms/step - loss: 0.6934 - auc: 0.6066 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 1.2768 - auc: 0.4660 - binary_accuracy: 0.6011 - precision: 0.1803 - recall: 0.3438 - val_loss: 1.2449 - val_auc: 0.3367 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 385ms/step - loss: 1.0946 - auc: 0.4775 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3144 - val_auc: 0.2989 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 366ms/step - loss: 1.0794 - auc: 0.4805 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3582 - val_auc: 0.2963 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoc

6/6 [==============================] - 0s 75ms/step - loss: 0.6914 - auc: 0.6009 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
[[0.70446169 0.58328092 0.77486908 0.         0.        ]
 [0.69337845 0.6066153  0.77486908 0.         0.        ]
 [0.69140959 0.60087991 0.77486908 0.         0.        ]]
Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 1.2184 - auc: 0.5074 - binary_accuracy: 0.7051 - precision: 0.2192 - recall: 0.2500 - val_loss: 1.2646 - val_auc: 0.3156 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 362ms/step - loss: 1.0831 - auc: 0.5241 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3564 - val_auc: 0.3191 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 352ms/step - loss: 1.0920 - auc: 0.4805 - binary_accuracy: 0

6/6 [==============================] - 0s 72ms/step - loss: 0.6720 - auc: 0.6003 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 1.3226 - auc: 0.4705 - binary_accuracy: 0.5253 - precision: 0.1698 - recall: 0.4219 - val_loss: 1.2473 - val_auc: 0.3656 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 350ms/step - loss: 1.1112 - auc: 0.4748 - binary_accuracy: 0.8174 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3046 - val_auc: 0.3355 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 374ms/step - loss: 1.0847 - auc: 0.4686 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3602 - val_auc: 0.3100 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoc

6/6 [==============================] - 0s 73ms/step - loss: 0.6221 - auc: 0.6179 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 1.2414 - auc: 0.4564 - binary_accuracy: 0.6657 - precision: 0.1429 - recall: 0.1719 - val_loss: 1.2549 - val_auc: 0.3364 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 362ms/step - loss: 1.0901 - auc: 0.5012 - binary_accuracy: 0.8174 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3229 - val_auc: 0.3264 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 344ms/step - loss: 1.0742 - auc: 0.5049 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3425 - val_auc: 0.3115 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoc

6/6 [==============================] - 0s 69ms/step - loss: 0.6168 - auc: 0.6270 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
[[0.67195225 0.60025144 0.77486908 0.         0.        ]
 [0.62214535 0.61785042 0.77486908 0.         0.        ]
 [0.61680841 0.62696421 0.77486908 0.         0.        ]]
Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 1.3126 - auc: 0.4729 - binary_accuracy: 0.5253 - precision: 0.1477 - recall: 0.3438 - val_loss: 1.2491 - val_auc: 0.3653 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 346ms/step - loss: 1.1068 - auc: 0.5079 - binary_accuracy: 0.8202 - precision: 0.5000 - recall: 0.0156 - val_loss: 1.3111 - val_auc: 0.3539 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 358ms/step - loss: 1.0930 - auc: 0.4575 - binary_accuracy: 0.8202 - 

6/6 [==============================] - 0s 59ms/step - loss: 0.6295 - auc: 0.5731 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 1.1969 - auc: 0.5427 - binary_accuracy: 0.7303 - precision: 0.1800 - recall: 0.1406 - val_loss: 1.2823 - val_auc: 0.3367 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 349ms/step - loss: 1.0962 - auc: 0.4945 - binary_accuracy: 0.8174 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3647 - val_auc: 0.3337 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 358ms/step - loss: 1.0878 - auc: 0.4687 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3322 - val_auc: 0.3498 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoc

6/6 [==============================] - 0s 71ms/step - loss: 0.6154 - auc: 0.5654 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 1.2709 - auc: 0.4886 - binary_accuracy: 0.6180 - precision: 0.1538 - recall: 0.2500 - val_loss: 1.2553 - val_auc: 0.3317 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 363ms/step - loss: 1.1023 - auc: 0.4957 - binary_accuracy: 0.8174 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3432 - val_auc: 0.2778 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 392ms/step - loss: 1.0782 - auc: 0.5196 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3618 - val_auc: 0.2898 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoc

6/6 [==============================] - 0s 71ms/step - loss: 0.6601 - auc: 0.5485 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
[[0.62951446 0.57306725 0.77486908 0.         0.        ]
 [0.61538589 0.56544626 0.77486908 0.         0.        ]
 [0.66006136 0.54847574 0.77486908 0.         0.        ]]
Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 1.3417 - auc: 0.5187 - binary_accuracy: 0.5590 - precision: 0.2112 - recall: 0.5312 - val_loss: 1.2666 - val_auc: 0.3612 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 340ms/step - loss: 1.1389 - auc: 0.4506 - binary_accuracy: 0.8090 - precision: 0.3000 - recall: 0.0469 - val_loss: 1.3695 - val_auc: 0.3522 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 353ms/step - loss: 1.1139 - auc: 0.4874 - binary_accuracy: 0.8174 - 

6/6 [==============================] - 0s 70ms/step - loss: 0.6668 - auc: 0.4971 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 1.3019 - auc: 0.4837 - binary_accuracy: 0.5618 - precision: 0.1567 - recall: 0.3281 - val_loss: 1.2407 - val_auc: 0.4122 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 365ms/step - loss: 1.1123 - auc: 0.5078 - binary_accuracy: 0.8034 - precision: 0.2000 - recall: 0.0312 - val_loss: 1.2946 - val_auc: 0.4034 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 340ms/step - loss: 1.0958 - auc: 0.4919 - binary_accuracy: 0.8202 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3207 - val_auc: 0.3926 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 4/100


6/6 [==============================] - 1s 87ms/step - loss: 0.6365 - auc: 0.5202 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 1/100
3/3 [==============================] - 5s 2s/step - loss: 1.2565 - auc: 0.4734 - binary_accuracy: 0.6404 - precision: 0.1667 - recall: 0.2500 - val_loss: 1.2556 - val_auc: 0.3636 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 372ms/step - loss: 1.1331 - auc: 0.4452 - binary_accuracy: 0.7949 - precision: 0.1538 - recall: 0.0312 - val_loss: 1.2960 - val_auc: 0.3677 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 443ms/step - loss: 1.0948 - auc: 0.4955 - binary_accuracy: 0.8146 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.3114 - val_auc: 0.3741 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 4/100


6/6 [==============================] - 0s 72ms/step - loss: 0.6410 - auc: 0.5074 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
[[0.66675216 0.49709302 0.77486908 0.         0.        ]
 [0.6364783  0.52019173 0.77486908 0.         0.        ]
 [0.64096963 0.50738525 0.77486908 0.         0.        ]]
Epoch 1/100
3/3 [==============================] - 10s 3s/step - loss: 1.3680 - auc: 0.4606 - binary_accuracy: 0.5281 - precision: 0.1486 - recall: 0.3438 - val_loss: 1.2482 - val_auc: 0.3571 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 481ms/step - loss: 1.1550 - auc: 0.5091 - binary_accuracy: 0.7753 - precision: 0.2647 - recall: 0.1406 - val_loss: 1.2861 - val_auc: 0.3434 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 415ms/step - loss: 1.1140 - auc: 0.5022 - binary_accuracy: 0.7921 -

6/6 [==============================] - 0s 67ms/step - loss: 0.6691 - auc: 0.4810 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 1/100
3/3 [==============================] - 9s 3s/step - loss: 1.3718 - auc: 0.4615 - binary_accuracy: 0.5056 - precision: 0.1667 - recall: 0.4375 - val_loss: 1.2383 - val_auc: 0.4016 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 429ms/step - loss: 1.1549 - auc: 0.5405 - binary_accuracy: 0.7584 - precision: 0.2381 - recall: 0.1562 - val_loss: 1.2424 - val_auc: 0.3867 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 384ms/step - loss: 1.0933 - auc: 0.5216 - binary_accuracy: 0.8146 - precision: 0.3333 - recall: 0.0312 - val_loss: 1.2557 - val_auc: 0.3768 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 4/100
3/3 [===

6/6 [==============================] - 0s 45ms/step - loss: 0.6233 - auc: 0.5055 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 1/100
3/3 [==============================] - 9s 3s/step - loss: 1.2665 - auc: 0.4620 - binary_accuracy: 0.6292 - precision: 0.1531 - recall: 0.2344 - val_loss: 1.2560 - val_auc: 0.3498 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 406ms/step - loss: 1.1179 - auc: 0.5366 - binary_accuracy: 0.7978 - precision: 0.2143 - recall: 0.0469 - val_loss: 1.2663 - val_auc: 0.3440 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 2s 543ms/step - loss: 1.0797 - auc: 0.5229 - binary_accuracy: 0.8118 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_loss: 1.2737 - val_auc: 0.3431 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 4/100


6/6 [==============================] - 0s 72ms/step - loss: 0.6148 - auc: 0.5031 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
[[0.6691044  0.48098677 0.77486908 0.         0.        ]
 [0.62334466 0.50549972 0.77486908 0.         0.        ]
 [0.61476034 0.50314271 0.77486908 0.         0.        ]]
Epoch 1/100
3/3 [==============================] - 9s 3s/step - loss: 1.9505 - auc: 0.4964 - binary_accuracy: 0.3455 - precision: 0.1737 - recall: 0.7031 - val_loss: 1.2717 - val_auc: 0.4052 - val_binary_accuracy: 0.6404 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 411ms/step - loss: 1.4480 - auc: 0.4203 - binary_accuracy: 0.5225 - precision: 0.1688 - recall: 0.4219 - val_loss: 1.2333 - val_auc: 0.3917 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 405ms/step - loss: 1.1948 - auc: 0.5717 - binary_accuracy: 0.7247 - 

6/6 [==============================] - 0s 79ms/step - loss: 1.1552 - auc: 0.4796 - binary_accuracy: 0.7801 - precision: 1.0000 - recall: 0.0233+ - ETA: 0s - loss: 1.1015 - auc: 0.5210 - binary_accuracy: 0.8542 - precision: 1.0000 - recall: 0.0667
Epoch 1/100
3/3 [==============================] - 10s 3s/step - loss: 1.5375 - auc: 0.5155 - binary_accuracy: 0.4831 - precision: 0.1842 - recall: 0.5469 - val_loss: 1.2465 - val_auc: 0.3516 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 460ms/step - loss: 1.3022 - auc: 0.4392 - binary_accuracy: 0.6433 - precision: 0.1881 - recall: 0.2969 - val_loss: 1.2444 - val_auc: 0.3361 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 473ms/step - loss: 1.1363 - auc: 0.5536 - binary_accuracy: 0.7612 - precision: 0.2308 - recall: 0.1406 - val_loss: 1.2547 - val_auc: 0.3361 - val_b

6/6 [==============================] - 1s 95ms/step - loss: 0.6765 - auc: 0.4858 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 1/100
3/3 [==============================] - 10s 3s/step - loss: 1.4867 - auc: 0.5038 - binary_accuracy: 0.4775 - precision: 0.1755 - recall: 0.5156 - val_loss: 1.2428 - val_auc: 0.3841 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 412ms/step - loss: 1.3084 - auc: 0.4293 - binary_accuracy: 0.6348 - precision: 0.1250 - recall: 0.1719 - val_loss: 1.2391 - val_auc: 0.3691 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 260ms/step - loss: 1.1535 - auc: 0.4881 - binary_accuracy: 0.7472 - precision: 0.1389 - recall: 0.0781 - val_loss: 1.2435 - val_auc: 0.3504 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 4/100
3/3 [==

6/6 [==============================] - 1s 108ms/step - loss: 0.6638 - auc: 0.4749 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
[[1.15518391 0.47957259 0.7801047  1.         0.02325581]
 [0.67651176 0.48577937 0.77486908 0.         0.        ]
 [0.66381234 0.47485855 0.77486908 0.         0.        ]]
Epoch 1/100
3/3 [==============================] - 10s 3s/step - loss: 1.9089 - auc: 0.5161 - binary_accuracy: 0.4972 - precision: 0.1925 - recall: 0.5625 - val_loss: 1.2414 - val_auc: 0.3809 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 490ms/step - loss: 1.4558 - auc: 0.4898 - binary_accuracy: 0.6011 - precision: 0.1803 - recall: 0.3438 - val_loss: 1.2370 - val_auc: 0.3730 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 485ms/step - loss: 1.3452 - auc: 0.5012 - binary_accuracy: 0.6685 

6/6 [==============================] - 1s 85ms/step - loss: 0.6855 - auc: 0.4862 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 1/100
3/3 [==============================] - 9s 3s/step - loss: 2.1620 - auc: 0.4815 - binary_accuracy: 0.4129 - precision: 0.1659 - recall: 0.5625 - val_loss: 1.2558 - val_auc: 0.3902 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 450ms/step - loss: 1.4964 - auc: 0.5453 - binary_accuracy: 0.5674 - precision: 0.2078 - recall: 0.5000 - val_loss: 1.2326 - val_auc: 0.3738 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 457ms/step - loss: 1.3790 - auc: 0.5203 - binary_accuracy: 0.6067 - precision: 0.1935 - recall: 0.3750 - val_loss: 1.2300 - val_auc: 0.3627 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 4/100
3/3 [===

6/6 [==============================] - 1s 97ms/step - loss: 0.6834 - auc: 0.4874 - binary_accuracy: 0.7749 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 2.2257 - auc: 0.4234 - binary_accuracy: 0.3567 - precision: 0.1429 - recall: 0.5156 - val_loss: 1.2696 - val_auc: 0.3457 - val_binary_accuracy: 0.6629 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 2s 562ms/step - loss: 1.6450 - auc: 0.5021 - binary_accuracy: 0.5225 - precision: 0.1845 - recall: 0.4844 - val_loss: 1.2403 - val_auc: 0.3226 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 361ms/step - loss: 1.4617 - auc: 0.4762 - binary_accuracy: 0.6096 - precision: 0.1622 - recall: 0.2812 - val_loss: 1.2408 - val_auc: 0.3364 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 4/100
3/3 [===

6/6 [==============================] - 0s 80ms/step - loss: 1.1539 - auc: 0.4672 - binary_accuracy: 0.7801 - precision: 1.0000 - recall: 0.0233
[[0.68552715 0.48617223 0.77486908 0.         0.        ]
 [0.68342918 0.48735073 0.77486908 0.         0.        ]
 [1.15393329 0.46723759 0.7801047  1.         0.02325581]]
Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 3.0178 - auc: 0.5220 - binary_accuracy: 0.4747 - precision: 0.1813 - recall: 0.5469 - val_loss: 1.2782 - val_auc: 0.4060 - val_binary_accuracy: 0.5955 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 376ms/step - loss: 2.9930 - auc: 0.4967 - binary_accuracy: 0.5225 - precision: 0.1807 - recall: 0.4688 - val_loss: 1.2374 - val_auc: 0.3850 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 381ms/step - loss: 2.7623 - auc: 0.5565 - binary_accuracy: 0.5309 - precisio

6/6 [==============================] - 0s 80ms/step - loss: 1.1366 - auc: 0.4819 - binary_accuracy: 0.7801 - precision: 1.0000 - recall: 0.0233
Epoch 1/100
3/3 [==============================] - 7s 2s/step - loss: 2.9764 - auc: 0.5521 - binary_accuracy: 0.5056 - precision: 0.2021 - recall: 0.5938 - val_loss: 1.2659 - val_auc: 0.4271 - val_binary_accuracy: 0.6517 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 1s 371ms/step - loss: 3.0163 - auc: 0.4441 - binary_accuracy: 0.4944 - precision: 0.1548 - recall: 0.4062 - val_loss: 1.2362 - val_auc: 0.4154 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 386ms/step - loss: 2.6161 - auc: 0.5774 - binary_accuracy: 0.5309 - precision: 0.2057 - recall: 0.5625 - val_loss: 1.2227 - val_auc: 0.4008 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 4/100
3/3 [===========

6/6 [==============================] - 0s 77ms/step - loss: 1.1438 - auc: 0.4551 - binary_accuracy: 0.7801 - precision: 1.0000 - recall: 0.0233+ - ETA: 0s - loss: 1.0913 - auc: 0.4251 - binary_accuracy: 0.8542 - precision: 1.0000 - recall: 0.0667   - ETA: 0s - loss: 1.1438 - auc: 0.4551 - binary_accuracy: 0.7801 - precision: 1.0000 - recall: 0.02
Epoch 1/100
3/3 [==============================] - 8s 3s/step - loss: 2.9060 - auc: 0.5044 - binary_accuracy: 0.5309 - precision: 0.2090 - recall: 0.5781 - val_loss: 1.2755 - val_auc: 0.3659 - val_binary_accuracy: 0.6517 - val_precision: 0.2000 - val_recall: 0.0357
Epoch 2/100
3/3 [==============================] - 1s 380ms/step - loss: 2.7207 - auc: 0.4985 - binary_accuracy: 0.5365 - precision: 0.1902 - recall: 0.4844 - val_loss: 1.2399 - val_auc: 0.3528 - val_binary_accuracy: 0.6854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/100
3/3 [==============================] - 1s 372ms/step - loss: 2.2308 - auc: 0.5459 - binary_accur

6/6 [==============================] - 0s 74ms/step - loss: 1.1313 - auc: 0.4668 - binary_accuracy: 0.7801 - precision: 1.0000 - recall: 0.0233  - ETA: 0s - loss: 1.1321 - auc: 0.4596 - binary_accuracy: 0.7812 - precision: 1.0000 - recall: 0.03 - ETA: 0s - loss: 1.1400 - auc: 0.4279 - binary_accuracy: 0.7750 - precision: 1.0000 - recall: 0.
[[1.13659894 0.4819296  0.7801047  1.         0.02325581]
 [1.1438489  0.4551383  0.7801047  1.         0.02325581]
 [1.13134885 0.46684474 0.7801047  1.         0.02325581]]
[array([[0.79791534, 0.59938717, 0.76963353, 0.        , 0.        ],
       [0.78631949, 0.57825267, 0.7329843 , 0.21428572, 0.06976745],
       [0.78203768, 0.59451604, 0.75916231, 0.        , 0.        ]]), array([[0.7464956 , 0.58108109, 0.77486908, 0.5       , 0.02325581],
       [0.75923735, 0.58202386, 0.76439792, 0.25      , 0.02325581],
       [0.73478353, 0.57880265, 0.76439792, 0.41666666, 0.11627907]]), array([[0.70446169, 0.58328092, 0.77486908, 0.        , 0.     

In [52]:
print(metrics)
print(*zip(lrs, np.mean(metrics, axis = 1)))

[array([[0.79791534, 0.59938717, 0.76963353, 0.        , 0.        ],
       [0.78631949, 0.57825267, 0.7329843 , 0.21428572, 0.06976745],
       [0.78203768, 0.59451604, 0.75916231, 0.        , 0.        ]]), array([[0.7464956 , 0.58108109, 0.77486908, 0.5       , 0.02325581],
       [0.75923735, 0.58202386, 0.76439792, 0.25      , 0.02325581],
       [0.73478353, 0.57880265, 0.76439792, 0.41666666, 0.11627907]]), array([[0.70446169, 0.58328092, 0.77486908, 0.        , 0.        ],
       [0.69337845, 0.6066153 , 0.77486908, 0.        , 0.        ],
       [0.69140959, 0.60087991, 0.77486908, 0.        , 0.        ]]), array([[0.67195225, 0.60025144, 0.77486908, 0.        , 0.        ],
       [0.62214535, 0.61785042, 0.77486908, 0.        , 0.        ],
       [0.61680841, 0.62696421, 0.77486908, 0.        , 0.        ]]), array([[0.62951446, 0.57306725, 0.77486908, 0.        , 0.        ],
       [0.61538589, 0.56544626, 0.77486908, 0.        , 0.        ],
       [0.66006136, 0.548